baseURL = 'https://dobefu.github.io/csb/'
languageCode = 'en-us'
title = 'Contentstack Bridge'
contentDir = 'content'
disableHugoGeneratorInject = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true

[params]
  linkTitle = 'CSB Docs'
  themeVariant = 'zen-dark'
  showVisitedLinks = false
  disableGeneratorVersion = true

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
