baseURL = 'https://dobefu.github.io/csb/'
languageCode = 'en-us'
title = 'Contentstack Bridge'
disableHugoGeneratorInject = true

[params]
  linkTitle = 'CSB Docs'
  themeVariant = 'zen-dark'
  showVisitedLinks = false
  disableGeneratorVersion = true

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
