baseURL = 'https://dobefu.github.io/csb/'
languageCode = 'en-us'
title = 'Contentstack Bridge'

[params]
  linkTitle = 'CSB Docs'
  themeVariant = 'zen-dark'
  showVisitedLinks = false

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
