name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

  test:
    name: "Test"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run tests
        run: go test --cover ./...

  deploy:
    name: "Release"
    needs: [test]
    steps:
      - uses: actions/checkout@v4

      - name: "Run GoReleaser"
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: "semver"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if:
      contains('refs/heads/main', github.ref)
